//
// Generated file, do not edit! Created by opp_msgtool 6.2 from Message/comMessage.msg.
//

#ifndef __COMMESSAGE_M_H
#define __COMMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0602
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class ComMessage;
/**
 * Class generated from <tt>Message/comMessage.msg:29</tt> by opp_msgtool.
 * <pre>
 * message ComMessage
 * {
 *     //parameter to allocate slots at ground station and tells me how much byte I have to send
 *     int B;
 *     //parameter set by the terminal that represent the gate at satellite
 *     int gate_index;
 *     //parameter set by GS to grant communication permission to the terminal that has requested for 
 *     bool grant;
 * }
 * </pre>
 */
class ComMessage : public ::omnetpp::cMessage
{
  protected:
    int B = 0;
    int gate_index = 0;
    bool grant = false;

  private:
    void copy(const ComMessage& other);

  protected:
    bool operator==(const ComMessage&) = delete;

  public:
    ComMessage(const char *name=nullptr, short kind=0);
    ComMessage(const ComMessage& other);
    virtual ~ComMessage();
    ComMessage& operator=(const ComMessage& other);
    virtual ComMessage *dup() const override {return new ComMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getB() const;
    virtual void setB(int B);

    virtual int getGate_index() const;
    virtual void setGate_index(int gate_index);

    virtual bool getGrant() const;
    virtual void setGrant(bool grant);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ComMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ComMessage& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline ComMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<ComMessage*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __COMMESSAGE_M_H

