//
// Generated file, do not edit! Created by opp_msgtool 6.2 from Message/contentMessage.msg.
//

#ifndef __CONTENTMESSAGE_M_H
#define __CONTENTMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0602
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class ContentMessage;
/**
 * Class generated from <tt>Message/contentMessage.msg:22</tt> by opp_msgtool.
 * <pre>
 * message ContentMessage
 * {
 *     //this is a field initialized only at runtime (depends on S from uniform distribution)
 *     int content;
 * }
 * </pre>
 */
class ContentMessage : public ::omnetpp::cMessage
{
  protected:
    int content = 0;

  private:
    void copy(const ContentMessage& other);

  protected:
    bool operator==(const ContentMessage&) = delete;

  public:
    ContentMessage(const char *name=nullptr, short kind=0);
    ContentMessage(const ContentMessage& other);
    virtual ~ContentMessage();
    ContentMessage& operator=(const ContentMessage& other);
    virtual ContentMessage *dup() const override {return new ContentMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getContent() const;
    virtual void setContent(int content);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ContentMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ContentMessage& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline ContentMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<ContentMessage*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __CONTENTMESSAGE_M_H

