[General]
network = System
sim-time-limit = 20s

cmdenv-express-mode = false
cmdenv-event-banners = false

# Default Configuration 
repeat = 35
seed-set = ${repetition}

*.t[*].a = 4B						# Max Size (bytes)	-> to provide a better interval of (a, b), check the Greatest and Lowest 
*.t[*].b = 100B						#						cases from the table values for 'M' in the Specifics
										
 
*.t[*].mean_T = 0.002s				# mean value of T 				

*.t[*].rng-0 = ancestorIndex(0) * 3 + 0				# *rng-0* 	: refers to the RNG of t[*] who's index specified (third argument) is '0'  
													# index 	: is a keyword which refers to the t[*] index (i.e. for terminal t[1], this line can be translated as: *.t[1].rng-0 = 1  
*.t[*].rng-1 = ancestorIndex(0) * 3 + 1
*.t[*].rng-2 = ancestorIndex(0) * 3 + 2

output-vector-file = ${resultdir}/${configname}/${iterationvars}-${repetition}.vec
output-scalar-file = ${resultdir}/${configname}/${iterationvars}-${repetition}.sca

#---------------------------------#
[Config throughputConsistencyTest]
**.N = ${N = 2, 4, 8, 16, 32}
**.K = 100
*.t[*].mean_T = 0.016s
num-rngs = ${N}*3

#---------------------------------#
[Config queueLengthConsistencyTest]
**.N = 18
**.K = 1
*.t[*].mean_T = ${T = 0.016s, 0.008s, 0.004s, 0.002s, 0.001s}
num-rngs = 18*3

#---------------------------------#
[Config degeneracyTest]
output-scalar-file = ${resultdir}/${configname}/degeneracy.sca
**.N = 0
**.K = 0
*.t[*].mean_T = 0s
*.t[*].a = 10^6
*.t[*].b = 10^7

#---------------------------------#
[Config throughputContinuityTest]
**.N = ${N = 2, 3, 4, 5, 6}
**.K = 100
*.t[*].mean_T = 0.016s
num-rngs = ${N}*3

#---------------------------------#
[Config queueLengthContinuityTest]
**.N = 18
**.K = 1
*.t[*].mean_T = ${T = 0.016s, 0.015s, 0.014s, 0.013s, 0.012s}
num-rngs = 18*3

#---------------------------------#
[Config warmUpTest]
sim-time-limit = 30s
**.N = ${N = 8, 16, 24, 32, 40}
**.K = ${K = 2, 3, 5, 10, 20, 50, 1000}
num-rngs = ${N}*3

#---------------------------------#
[Config simulationTest]
extends = warmUpTest
warmup-period = 10s
repeat = 35

#---------------------------------#
[Config SimpleScenario]
sim-time-limit = 5s
**.N=2
**.K=100
num-rngs = 2*3

#---------------------------------#
[Config varianceTest]
extends = simulationTest
repeat = 200

#---------------------------------#
[Config varianceN16K5]
**.N=16
**.K=5
num-rngs = 3*16
warmup-period = 10s
repeat = 500
output-scalar-file = ${resultdir}/${configname}/$N=16, $K=5-${repetition}.sca
