[General]
network = System
sim-time-limit = 0.8s

cmdenv-express-mode = false
cmdenv-event-banners = false

# Default Configuration 
**.N = 2						# Number of Terminals (defined in System.ned)
**.K = 1000

num-rngs = 2					# Create a n° of Random-Number-Generator Streams as many as the Terminals

*.t[*].a = 100KiB						# Min Size (bytes)
*.t[*].b = 1000KiB						# Max Size (bytes)	-> to provide a better interval of (a, b), check the Greatest and Lowest 
										#						cases from the table values for 'M' in the Specifics
 
*.t[*].lambda = 0.05s					# Rate of T -> 	Considered a third of the Time-Frame's duration (80/3 ms) 
										#			  	to also provide the chance of NO packets in the queue of a terminal  

*.t[*].rng-0 = index			# *rng-0* 	: refers to the RNG of t[*] who's index specified (third argument) is '0'  
								# index 	: is a keyword which refers to the t[*] index (i.e. for terminal t[1], this line can be translated as: *.t[1].rng-0 = 1  
*.t[*].rng-1 = index
*.t[*].rng-2 = index